"""update columns

Revision ID: 02b484d6c1cf
Revises: 92859629f4cd
Create Date: 2023-07-21 08:11:20.607555

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "02b484d6c1cf"
down_revision = "92859629f4cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
