"""update columns

Revision ID: 92859629f4cd
Revises: b9aac3957d03
Create Date: 2023-07-21 08:09:42.567562

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "92859629f4cd"
down_revision = "b9aac3957d03"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
