"""init

Revision ID: b9aac3957d03
Revises: 
Create Date: 2023-07-17 09:36:45.069988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9aac3957d03'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_status', sa.Enum('FRIENDS', 'SUBSCRIBER', 'SEND_FRIEND_REQUEST', name='relationshiptypes'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('relationship_status')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('users_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_from_id', sa.Integer(), nullable=False),
    sa.Column('user_to_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_from_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_relationships')
    op.drop_table('users')
    op.drop_table('relationship_types')
    # ### end Alembic commands ###
